import pytest
from app.utils.formatting import format_seconds
from app.utils.parsers import parse_transcript_file

def test_format_seconds():
    assert format_seconds(0) == "[00:00]"
    assert format_seconds(65) == "[01:05]"
    assert format_seconds(3600) == "[01:00:00]"
    assert format_seconds(3665) == "[01:01:05]"
    assert format_seconds(0.5) == "[00:00]"

def test_parse_transcript_file_clean():
    content = """YouTube Video Transcript
Generated: 2024-01-01
Transcript Source: YOUTUBE

================================================================================

[00:00] Hello world
[00:05] This is a test

================================================================================

Generated by YouTube Summarizer
"""
    parsed = parse_transcript_file(content)
    assert "[00:00] Hello world" in parsed
    assert "[00:05] This is a test" in parsed
    assert "YouTube Video Transcript" not in parsed
    assert "Generated by" not in parsed

def test_parse_transcript_file_raw():
    content = "Just some raw text content without headers"
    parsed = parse_transcript_file(content)
    assert parsed == content.strip()
